import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Capt. America Bobblehead",
    is_topSeller: "Yes",
    productImage: "/assets/images/captain-america-bobblehead.jpg",
    rating: 5,
    price: "299",
    categoryName: "Marvel",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Iron Man Bobblehead",
    is_topSeller: "Yes",
    productImage: "/assets/images/ironman-bobblehead.png",
    rating: 4,
    price: "499",
    categoryName: "Marvel",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Hulk Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/hulk-bobblehead.jpg",
    rating: 3,
    price: "298",
    categoryName: "Marvel",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Spiderman Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/spiderman.jpg",
    rating: 2,
    price: "329",
    categoryName: "Marvel",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Ronaldo Bobblehead",
    is_topSeller: "Yes",
    productImage: "/assets/images/roanldo-bobblehead.jpg",
    rating: 1,
    price: "309",
    categoryName: "Football",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Pikachu Bobblehead",
    is_topSeller: "Yes",
    productImage: "/assets/images/pikachu-bobblehead.jpg",
    rating: 5,
    price: "239",
    categoryName: "Pokemons",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Shinchan Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/Shinchan-bobblehead.jpg",
    rating: 4,
    price: "248",
    categoryName: "Anime",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Naruto Bobblehead",
    is_topSeller: "Yes",
    productImage: "/assets/images/Naruto-bobblehead.jpg",
    rating: 3,
    price: "249",
    categoryName: "Anime",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Krillin Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/krillin.jpg",
    rating: 2,
    price: "289",
    categoryName: "Anime",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Charizard Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/charizard.jpg",
    rating: 1,
    price: "399",
    categoryName: "Pokemons",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Goku Bobblehead Keychain",
    is_topSeller: "Yes",
    productImage: "/assets/images/gokuKeychain.jpg",
    rating: 5,
    price: "349",
    categoryName: "Keychains",
    quantity: "",
  },
  {
    _id: uuid(),
    title: "Batman Bobblehead",
    is_topSeller: "No",
    productImage: "/assets/images/batman.jpg",
    rating: 4,
    price: "328",
    categoryName: "DC",
    quantity: "",
  },
];
